---
- name: Login to ACR using Podman
  containers.podman.podman_login:
    registry: acrcasopractico2.azurecr.io
    username: "{{ acr_username }}"
    password: "{{ acr_password }}"

    
- name: Create secret for ACR authentication
  k8s:
    state: present
    kind: Secret
    api_version: v1
    name: acr-secret
    namespace: "practica2"
    resource_definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: acr-secret
        namespace: "practica2"
      type: kubernetes.io/dockerconfigjson
      data:
        .dockerconfigjson: "{{ lookup('file', '/home/ubuntu/.config/containers/auth.json') | b64encode }}"

