- name: Expose backend service via LoadBalancer
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "{{ app.backend.name }}-service"
        namespace: "{{ app_namespace }}"
      spec:
        type: LoadBalancer
        selector:
          app: "{{ app.backend.name }}"
        ports:
          - protocol: TCP
            port: 80
            targetPort: 6379

