---
- name: Create PersistentVolumeClaim for the application
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'roles/aks/templates/persistent_volume_claim.yaml.j2') }}"

- name: Create deployment for backend
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'roles/aks/templates/app_template.yaml.j2') }}"
    namespace: "practica2"

- name: Create frontend deployment (if any)
  kubernetes.core.k8s:
    state: present
    definition: "{{ lookup('template', 'roles/aks/templates/frontend_template.yaml.j2') }}"
    namespace: "practica2"
