---
- name: Ensure the namespace exists
  k8s:
    state: present
    kind: Namespace
    name: "practica2"
    api_version: v1

- name: Create Kubernetes secret for ACR authentication
  import_tasks: tasks/create_secret.yaml  # Ruta correcta al archivo de tarea

- name: Deploy application to AKS
  import_tasks: tasks/create_deployment.yaml  # Ruta correcta al archivo de tarea

- name: Create LoadBalancer service
  import_tasks: tasks/create_service.yaml  # Ruta correcta al archivo de tarea

