---
- name: Setup ACR and images
  hosts: localhost
  vars_files:
    - group_vars/vault.yaml
  tasks:
    - name: Pull, build, tag and push images to ACR
      include_role:
        name: acr

- name: Setup Webserver
  hosts: vm
  vars_files:
    - group_vars/vault.yaml
  tasks:
    - name: Configure VM with Podman and deploy web server
      include_role:
        name: vm

- name: Setup AKS
  hosts: localhost
  vars_files:
    - group_vars/vault.yaml
  tasks:
    - name: Deploy app to AKS
      include_role:
        name: aks
